##########################################################################
#  <.HTTP_METHOD> indicate optional so it can be .GET .PUT .POST .DELETE
#
#  system.addons.properties.files=addon1.properties,addon2.properties
#  system.custom.xxxx=XXXX

#  restapi.xxx.plugin.implementation=hl.restapi.plugins.SysOutPlugin
#  restapi.xxx.optional.disabled=post,delete,update  - true(all),get,update,delete,post
#  restapi.xxx.optional.mapped.url=
#  restapi.xxx.optional.echo.jsonattr.prefix=echo.
#  restapi.xxx.optional.mandatory.jsonattrs<.HTTP_METHOD>=field1,field2
#  restapi.xxx.optional.proxy.url<.HTTP_METHOD>=http://www.google.com
#  restapi.xxx.optional.static.web=false  (default:false)
#
##########################################################################

system.addons.properties.files=restapi_unittest.properties

system.custom.objml.config.plugins.folder=/Users/onghuilam/git/hl-objml-serv/src/main/resources/plugins
system.custom.objml.config.native-lib.folder=/Users/onghuilam/git/hl-objml-serv/src/main/resources/lib-native
system.custom.objml.config.test-image.folder=/Users/onghuilam/git/hl-objml-serv/src/main/resources/test-images

restapi.html.optional.mapped.url=/html/
restapi.html.optional.static.web=true

restapi.objml.optional.mapped.url=/objml/{action}
restapi.objml.plugin.implementation=hl.objml.serv.api.ObjMLPluginApi
#----
restapi.objml-list.optional.mapped.url=/objml
restapi.objml-list.optional.proxy.url.GET=/objml/list
#----
restapi.objml-info.optional.mapped.url=/objml/plugin/{className}
restapi.objml-info.optional.proxy.url.GET=/objml/info?className={className}
#----
restapi.objml-detect.optional.mapped.url=/objml/plugin/{className}/detect/{imgFileName}
restapi.objml-detect.optional.proxy.url.GET=/objml/detect?className={className}&imageFileName={imgFileName}
#----
